### ISSUE TITLE
Cannot find module 'react-static-plugin-less'

### ISSUE THREAD

**Issue by koorchik** [react-static/react-static#1150]
```
Error: Cannot find module 'react-static-plugin-less'
```

### Environment

Run and copy the result of:

`npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers` 

here:

```

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 27.46 GB / 47.05 GB
    Container: Yes
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.15.3 - ~/n/bin/node
    npm: 6.4.1 - ~/n/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 66.0.3
  npmPackages:
    react: ^16.8.2 => 16.8.6 
    react-addons-css-transition-group: ^15.6.2 => 15.6.2 
    react-dom: ^16.8.2 => 16.8.6 
    react-responsive-carousel: ^3.1.49 => 3.1.49 
    react-router-dom: ^5.0.0 => 5.0.0 
    react-static: ^7.0.9 => 7.0.9 
    react-static-plugin-less: ^7.0.8 => 7.0.8 
    react-static-plugin-reach-router: ^7.0.8 => 7.0.8 
    react-static-plugin-sass: ^7.0.8 => 7.0.8 
    react-static-plugin-sitemap: ^7.0.8 => 7.0.8 
    react-static-plugin-source-filesystem: ^7.0.8 => 7.0.8 
    react-youtube: ^7.9.0 => 7.9.0 

```

of course include any other package versions here if relevant. 

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  react-static-plugin-less:
2.  try load it

### Expected Behavior

The module should be loaded but you will get
```Error: Cannot find module 'react-static-plugin-less'````

**Comment by fameoflight** [comment]
as a workaround create plugins directory and then create react-static-plugin-less in it, and copy node_modules/react-static-plugin-less/src/node* to plugins/react-static-plugin-less

**Comment by fameoflight** [comment]
@tannerlinsley  any ideas on this would love to remove my workaround here. I can repro this with 7.0.10 as well if that helps.

**Comment by pmogollons** [comment]
Im having the same issue after upgrading to react-static 7 from 6

**Comment by SleeplessByte** [comment]
Should have been fixed in #1172
